### ISSUE TITLE
make fail

### ISSUE THREAD

**Issue by LucasXu0** [vovkos/protolesshooks#1]
`mkdir build && cd build && cmake && make`

After that, I faced some problems.

`plh_Hook_amd64_gcc.cpp:136:9: error: use of undeclared
      identifier 'g_hookMgr'
        return g_hookMgr.removeFrame(rbp);
               ^
4 errors generated.`

**Comment by vovkos** [comment]
Most likely, your compiler doesn't allow the C++11 extensions by default, and hence, doesn't recognize the ``thread_local`` keyword.

Try re-running cmake as such:

```
cd ./build
cmake -DCMAKE_CXX_FLAGS=-std=c++11 ..
make
```

**Comment by LucasXu0** [comment]
Thanks! 😁
